import os
import sys
import rtconfig

if os.getenv('RTT_ROOT'):
    RTT_ROOT = os.getenv('RTT_ROOT')
else:
    RTT_ROOT = os.path.normpath(os.getcwd() + '/../../..')

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
from building import *

TARGET = 'rtthread_acm32p4xx.' + rtconfig.TARGET_EXT

# DMA / pin conflict check: print map + conflicts, inject #warning into
# rtconfig.h, then continue build (no SCons abort).
rtconfig.check_bsp_resources(os.path.join(os.getcwd(), 'rtconfig.h'), fatal=False)

env = Environment(tools = ['mingw'],
    AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
    CC = rtconfig.CC, CFLAGS = rtconfig.CFLAGS,
    AR = rtconfig.AR, ARFLAGS = '-rc',
    LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)

if rtconfig.PLATFORM in ['iccarm']:
    env.Replace(CCCOM = ['$CC $CFLAGS $CPPFLAGS $_CPPDEFFLAGS $_CPPINCFLAGS -o $TARGET $SOURCES'])
    env.Replace(ARFLAGS = [''])
    env.Replace(LINKCOM = ['$LINK $SOURCES $LINKFLAGS -o $TARGET --map project.map'])

Export('RTT_ROOT')
Export('rtconfig')

# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT, has_libcpu=False)

# ETH/iperf: lwIP heap from RT-Thread heap (default MEM_SIZE=1600 is too small).
if GetDepend(['BSP_USING_ETH']):
    env.AppendUnique(CPPDEFINES = [
        'MEM_LIBC_MALLOC=1',
        'MEMP_NUM_TCPIP_MSG_INPKT=16',
    ])

# make a building
DoBuilding(TARGET, objs)
