Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

# ETH driver is optional: drop source + only add lwIP headers when enabled
if GetDepend('BSP_USING_ETH'):
    CPPPATH += [RTT_ROOT + '/components/net/lwip/lwip-2.1.2/src/include',
                RTT_ROOT + '/components/net/lwip/port']
else:
    SrcRemove(src, 'drv_eth.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
