Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

# ETH driver is optional: drop source + only add lwIP headers when enabled
if GetDepend('BSP_USING_ETH'):
    CPPPATH += [RTT_ROOT + '/components/net/lwip/lwip-2.1.2/src/include',
                RTT_ROOT + '/components/net/lwip/port']
else:
    SrcRemove(src, 'drv_eth.c')

# USB device (FSUSB): <drivers/usb_device.h> lives in components/drivers/include
# (also added by serial/i2c/... sub-SConscripts; explicit for clarity).
if GetDepend('BSP_USING_FSUSB'):
    CPPPATH += [RTT_ROOT + '/components/drivers/include']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
