Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

# add lwIP include path when ETH is enabled
if GetDepend('BSP_USING_ETH'):
    CPPPATH += [RTT_ROOT + '/components/net/lwip/lwip-2.1.2/src/include',
                RTT_ROOT + '/components/net/lwip/port']

# remove other no use files
# SrcRemove(src, '*.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
